// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjOMnFnRLkAwIEKSfVk0NcKTPoOX5RF-0',
    appId: '1:317962514237:web:d3757036b6e637adc75f54',
    messagingSenderId: '317962514237',
    projectId: 'saloon-d8967',
    authDomain: 'saloon-d8967.firebaseapp.com',
    storageBucket: 'saloon-d8967.appspot.com',
    measurementId: 'G-S97PVSTC6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzUww4MvwKy6vrJOlyQ0ezFOAKUqUvQJQ',
    appId: '1:317962514237:android:6a767d26a6d3dcd0c75f54',
    messagingSenderId: '317962514237',
    projectId: 'saloon-d8967',
    storageBucket: 'saloon-d8967.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsUK-oBx-uMc2-z4wIC9Ezru0ShaQbW6s',
    appId: '1:317962514237:ios:3e3a47e370d5dd23c75f54',
    messagingSenderId: '317962514237',
    projectId: 'saloon-d8967',
    storageBucket: 'saloon-d8967.appspot.com',
    iosBundleId: 'com.example.barbarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsUK-oBx-uMc2-z4wIC9Ezru0ShaQbW6s',
    appId: '1:317962514237:ios:3e3a47e370d5dd23c75f54',
    messagingSenderId: '317962514237',
    projectId: 'saloon-d8967',
    storageBucket: 'saloon-d8967.appspot.com',
    iosBundleId: 'com.example.barbarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjOMnFnRLkAwIEKSfVk0NcKTPoOX5RF-0',
    appId: '1:317962514237:web:503d22c371dfcf9fc75f54',
    messagingSenderId: '317962514237',
    projectId: 'saloon-d8967',
    authDomain: 'saloon-d8967.firebaseapp.com',
    storageBucket: 'saloon-d8967.appspot.com',
    measurementId: 'G-VDQ26SJ573',
  );
}
